config/routes.rb
Rails.application.routes.draw do
  resources :deals do
    get :live, on: :collection
  end

  resources :admins

  resources :users

  resources :orders, only: :create

  controller :sessions do
    post :login, action: :create
    delete :logout, action: :destroy
  end

  root to: 'admins#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  validates :name, presence: true
end

app/models/deal.rb
class Deal < ActiveRecord::Base

  before_destroy :check_destroyablity
  before_save :check_publishability, if: ->{ live }

  has_many :orders, inverse_of: :deal, dependent: :restrict_with_error
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }

  validates :title, presence: true

  with_options if: ->{ publishable } do |deal|
    deal.validates :description, :price, :discounted_price, :quantity, :publish_date, presence: true
    deal.validates :quantity, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    deal.validates :price, numericality: {
                                    greater_than: :discounted_price,
                                    message: 'Price must be greater than Discounted Price.'
                                  }, if: ->{ price? && discounted_price? }
    deal.validates :publish_date, uniqueness: { scope: :live }, allow_blank: true, if: -> { live }
  end

  validates :publishable, acceptance: { accept: true, message: 'required to publish!' }, if: -> { live }

  scope :live_deals, ->{ where(live: true) }

  scope :publishable_deals, ->{ where(publishable: true) }

  scope :publishable_deals_for_today, ->{ where(publishable: true, publish_date: Date.current) }

  def make_live
    self.update_column(:live, true)
  end

  private

    def check_destroyablity
      if live
        errors.add(:base, 'Cannot delete a live deal!')
        false
      end
    end

    def check_publishability
      if Deal.live_deals.many? || publish_date != Date.current
        errors.add(:base, 'Cannot publish deal!')
        false
      end
    end

    def self.unpublish_old_deal
      old_deal = Deal.live_deals.first
      old_deal.update_column(:live, false) if old_deal
    end


end

app/models/order.rb
class Order < ActiveRecord::Base

  before_validation :set_discount, :set_sale_price, on: :create, if: ->{ user && deal }
  before_save :update_deal, on: :create

  belongs_to :user, counter_cache: true
  belongs_to :deal, autosave: true

  validates :user, :deal, presence: true
  validates :discount, :sale_price, presence: true, if: ->{ user && deal }
  validates :discount, numericality: {
                                        greater_than_or_equal_to: 0,
                                        less_than_or_equal_to: 5
                                     }, allow_blank: true
  validates :deal, uniqueness: { scope: :user, message: 'can only be purchased once!' }
  validate :check_deal_availability, if: ->{ user && deal }

  private

    def update_deal
      self.deal.quantity = deal.quantity - 1
    end

    def set_discount
      self.discount ||= user.orders_count > 5 ? 5 : user.orders_count
    end

    def set_sale_price
      self.sale_price ||= deal.discounted_price - deal.discounted_price * discount / 100
    end

    def check_deal_availability
      unless deal.live && deal.publishable && deal.quantity > 0
        errors.add(:base, 'Deal cannot be purchased!')
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :orders, inverse_of: :user

  validates :name, presence: true

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :authenticate_admin
  before_action :set_admin, only: [:show, :edit, :update, :destroy]


  def index
    @admins = Admin.all.order(:name)
    flash[:error] = @admins.empty? ? 'No records to display!' : nil
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admins_path, notice: 'Admin has been successfully created.'
    else
      render :new
    end
  end

  def update
    if @admin.update(admin_params)
      redirect_to admins_path, notice: 'Admin has been successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      flash[:notice] = 'Admin has been successfully deleted.'
    else
      flash[:error] = @admin.errors.full_messages.join('<br>')
    end
    redirect_to admins_path
  end

  private

    def set_admin
      @admin = Admin.find_by(id: params[:id])
      redirect_to admins_path, error: 'Admin does not exist!' unless @admin
    end

    def admin_params
      params.require(:admin).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate

  private

    def current_user
      @current_user ||= Admin.find_by(id: session[:admin_id]) || User.find_by(id: session[:user_id])
    end
    helper_method :current_user

    def authenticate
      redirect_to users_path unless current_user
    end

    def authenticate_admin
      redirect_to users_path unless current_user.is_a? Admin
    end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  def index
    @deals = Deal.all.order(:title)
    flash[:error] = @deals.empty? ? 'No records to display!' : nil
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save
      redirect_to deals_path, notice: 'deal has been successfully created.'
    else
      flash[:error] = @deal.errors.messages[:base]
      render :new
    end
  end

  def update
    if @deal.update(deal_params)
      redirect_to deals_path, notice: 'deal has been successfully updated.'
    else
      flash[:error] = @deal.errors.messages[:base]
      render :edit
    end
  end

  def destroy
    if @deal.destroy
      flash[:notice] = 'deal has been successfully deleted.'
    else
      flash[:error] = @deal.errors.full_messages.join('<br>')
    end
    redirect_to deals_path
  end

  def live
    @deal = Deal.find_by(live: true)
    flash[:error] = 'No deal for today!' unless @deal
  end

  private

    def set_deal
      @deal = Deal.find_by(id: params[:id])
      redirect_to deals_path, error: 'deal does not exist!' unless @deal
    end

    def deal_params
      params.require(:deal).permit(:title, :description, :price, :discounted_price, :quantity, :publish_date, :publishable, :live)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @order = Order.new(user_id: current_user.id, deal_id: params[:deal_id])
    if @order.save
      flash[:notice] = 'Order has been successfully placed.'
    else
      flash[:error] = @order.errors.full_messages.join('<br>')
    end
    redirect_to live_deals_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authenticate

  def create
    session[:admin_id] = params[:admin_id]
    session[:user_id] = params[:user_id]
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate, :authenticate_admin, only: :index


  def index
    @users = User.all.order(:name)
    flash[:error] = @users.empty? ? 'No records to display!' : nil
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'user has been successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'user has been successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'user has been successfully deleted.'
    else
      flash[:error] = @user.errors.full_messages.join('<br>')
    end
    redirect_to users_path
  end

  private

    def set_user
      @user = User.find_by(id: params[:id])
      redirect_to users_path, error: 'user does not exist!' unless @user
    end

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/_admin.html.erb
<tr>
  <td><%= admin.name %></td>
  <td>
      <%= link_to 'Edit', edit_admin_path(admin) %> |
      <%= link_to 'Delete', admin, method: :delete, data: { confirm: "Are you sure you want to delete #{ admin.name }?" } unless admin == current_user %>
  </td>
</tr>

app/views/admins/_form.html.erb
<%= form_for @admin, html: { class: 'form-horizontal' } do |f| %>
  <div class="input_form container">
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end -%>

app/views/admins/edit.html.erb
<h1 class="main-heading panel-heading">Edit Admin</h1>

<%= render 'form' %>

<h4 class="row">
    <%= link_to 'Back', admin_path(@admin), class: 'col-sm-offset-2 col-sm-2' %>
  </h4>

app/views/admins/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="main-heading panel-heading col-sm-5">Listing Admins</h1>
    <%= link_to 'New Admin', new_admin_path, class: "pull-right btn btn-primary" %>
  </div>


  <% unless @admins.empty? %>
    <table class="table">
      <thead>
        <th>Name</th>
      </thead>
      <tbody>
        <%= render @admins %>
      </tbody>
    </table>

    <% end -%>

</div>

app/views/admins/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="main-heading panel-heading col-sm-5">New Admin</h1>
    <%= link_to 'All Admins', admins_path, class: "pull-right btn btn-primary" %>
  </div>

  <%= render 'form' %>

</div>

app/views/application/_notice.html.erb
<% if flash[:alert] %>
  <p id="alert" class="alert alert-info"><%= flash[:alert] %></p>
<% elsif flash[:notice] -%>
  <p id="notice" class="alert alert-success"><%= flash[:notice] %></p>
<% elsif flash[:error] -%>
  <p id="error" class="alert alert-danger"><%= flash[:error] %></p>
<% end -%>
<% flash.clear %>

app/views/deals/_deal.html.erb
<tr>
  <td><%= deal.title %></td>
  <td><%= deal.description %></td>
  <td><%= deal.price %></td>
  <td><%= deal.discounted_price %></td>
  <td><%= deal.quantity %></td>
  <td><%= deal.publish_date %></td>
  <td><%= deal.publishable %></td>
  <td><%= deal.live %></td>
  <% if current_user.is_a? Admin %>
    <td>
        <%= link_to 'Edit', edit_deal_path(deal) %> |
        <%= link_to 'Delete', deal, method: :delete, data: { confirm: "Are you sure you want to delete #{ deal.title }?" } unless deal == current_user %>
    </td>
  <% end -%>
</tr>

app/views/deals/_form.html.erb
<%= form_for @deal, html: { class: 'form-horizontal' } do |f| %>
  <div class="input_form container">
    <div class="form-group">
      <%= f.label :title, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :price, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :discounted_price, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :discounted_price, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :quantity, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :quantity, class: 'form-control' %>
      </div>
    </div>
      <div class="form-group">
        <%= f.label :publish_date, class: 'col-md-2 control-label required' %>
        <div class="col-md-9 col-md-offset-2 input-group date date-field" data-provide: 'datepicker'>
          <%= f.text_field :publish_date, class: 'form-control' %>
          <div class="input-group-addon">
            <!-- <span class="glyphicon glyphicon-th"></span> -->
          </div>
        </div>
      </div>
    <div class="form-group">
        <%= f.label :publishable, 'Mark publishable?', class: 'col-sm-2 control-label required' %>
      <div class="col-sm-2">
        <%= f.check_box :publishable, class: 'form-control required' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end -%>

app/views/deals/edit.html.erb
<h1 class="main-heading panel-heading">Edit deal</h1>

<%= render 'form' %>

<h4 class="row">
    <%= link_to 'Back', deals_path, class: 'col-sm-offset-2 col-sm-2' %>
  </h4>

app/views/deals/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="main-heading panel-heading col-sm-5">Listing deals</h1>
    <%= link_to 'New Deal', new_deal_path, class: "pull-right btn btn-primary" %>
  </div>

  <% unless @deals.empty? %>
    <table class="table">
      <thead>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Discounted Price</th>
        <th>Quantity</th>
        <th>Publish Date</th>
        <th>Publishable</th>
        <th>Live</th>
      </thead>
      <tbody>
        <%= render @deals %>
      </tbody>
    </table>

    <% end -%>

</div>

app/views/deals/live.html.erb
<div class="container-fluid">
  <% if @deal %>
    <div class="row">
      <h1 class="main-heading panel-heading">DEAL OF THE DAY!</h1>
    </div>
    <div class="container">
      <table class="table">
        <thead>
          <th>Title</th>
          <th>Description</th>
          <th>Price</th>
          <th>Discounted Price</th>
          <th>Quantity</th>
          <th>Publish Date</th>
          <th>Publishable</th>
          <th>Live</th>
        </thead>
        <tbody>
          <tr>
            <td><%= @deal.title %></td>
            <td><%= @deal.description %></td>
            <td><%= @deal.price %></td>
            <td><%= @deal.discounted_price %></td>
            <td><%= @deal.quantity %></td>
            <td><%= @deal.publish_date %></td>
            <td><%= @deal.publishable %></td>
            <td><%= @deal.live %></td>
          </tr>
        </tbody>
      </table>
      <% if current_user.is_a? User %>
        <% if current_user.orders_count > 0 %>
          <h3>
            <div class="label label-info">You have an additional <%= current_user.orders_count %>% discount!</div>
          </h3>
          <h4>
            New Sale Price: <%= @deal.discounted_price - @deal.discounted_price * current_user.orders_count / 100 %>
          </h4>
        <% end -%>
        <%= link_to 'BUY', orders_path(deal_id: @deal.id), method: :post, class: 'btn btn-success'  %>
      </div>
      <% end -%>
    <% end -%>
</div>

app/views/deals/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="main-heading panel-heading col-sm-5">New Admin</h1>
    <%= link_to 'All Admins', admins_path, class: "pull-right btn btn-primary" %>
  </div>

  <%= render 'form' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campus Drive+</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid navigation">
      <div class="navbar-header">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li class="<%= params[:action] == 'live' ? 'active' : '' %>"><%= link_to 'HOME', live_deals_path %></li>
              <% if current_user.is_a? Admin %>
                <li class="<%= params[:controller] == 'admins' ? 'active' : '' %>"><%= link_to 'ADMINS', admins_path %></li>
              <% end -%>
              <li class="<%= params[:controller] == 'deals' && params[:action] != 'live' ? 'active' : '' %>"><%= link_to 'DEALS', deals_path %></li>
            <% end -%>
            <li class="<%= params[:controller] == 'users' ? 'active' : '' %>"><%= link_to 'USERS', users_path %></li>
          </ul>
        </div>
        <div class="navbar-right">
            <%= form_tag '/login' do %>
              <%= select_tag "admin_id", options_from_collection_for_select(Admin.all, "id", "name", current_user.try(:id)), prompt: 'Select Admin', class: 'dropdown pull-right' %>
              <%= select_tag "user_id", options_from_collection_for_select(User.all, "id", "name", current_user.try(:id)), prompt: 'Select User', class: 'dropdown pull-right' %>
              <%= submit_tag 'Select' %>
            <% end -%>
        </div>
      </div>
    </nav>
    <div class='container'>
      <%= render partial: 'notice' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_order.html.erb
<tr>
  <td><%= order.deal.title %></td>
  <td><%= order.discount %>%</td>
  <td><%= order.sale_price %></td>
</tr>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
  <div class="input_form container">
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label required' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end -%>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td>
      <%= link_to 'View', user %>
      <% if current_user.is_a? Admin %>
       | <%= link_to 'Edit', edit_user_path(user) %> |
        <%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure you want to delete #{ user.name }?" } %>
      <% end -%>
  </td>
</tr>

app/views/users/edit.html.erb
<h1 class="main-heading panel-heading">Edit user</h1>

<%= render 'form' %>

<h4 class="row">
    <%= link_to 'Back', users_path, class: 'col-sm-offset-2 col-sm-2' %>
  </h4>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="main-heading panel-heading col-sm-5">Listing users</h1>
    <%= link_to 'New user', new_user_path, class: "pull-right btn btn-primary"  if current_user.is_a? Admin %>
  </div>

  <% unless @users.empty? %>
    <table class="table">
      <thead>
        <th>Name</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>

  <% end -%>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="main-heading panel-heading col-sm-5">New Admin</h1>
    <%= link_to 'All Admins', admins_path, class: "pull-right btn btn-primary" %>
  </div>

  <%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h1 class="main-heading panel-heading">Hi <%= @user.name %>!</h1>
    <%= link_to 'Edit user', edit_user_path(@user), class: "pull-right btn btn-primary" %>
  </div>
  <div class="container">
    <% unless @user.orders.empty? %>
      <table class="table">
        <thead>
          <th>Deal</th>
          <th>Discount</th>
          <th>Sale Price</th>
        </thead>
        <tbody>
          <%= render @user.orders %>
        </tbody>
      </table>
    <% end -%>
  </div>
</div>